name: flutter_services_binding
description: A subset of WidgetsFlutterBinding specifically for ServicesBinding.
version: 0.1.0
repository: https://github.com/felangel/flutter_services_binding
homepage: https://github.com/felangel/flutter_services_binding

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0
